// Generated by ts-to-zod
import { z } from "zod";

export const stopPointSchema = z.object({
  type: z.string(),
  id: z.string(),
  name: z.string(),
  naptanId: z.string(),
  lat: z.union([z.number(), z.string()]),
  lon: z.union([z.number(), z.string()]),
  modes: z.array(z.string()),
  lines: z.array(z.string()),
});
