// Generated by ts-to-zod
import { z } from "zod";
import { Mode } from "./NetworkTypes";

export const modeSchema = z.nativeEnum(Mode);

export const lineSchema = z.object({
  type: z.string(),
  lineName: z.string(),
  displayName: z.string(),
  mode: modeSchema.optional(),
});

export const lineSegmentSchema = z.object({
  type: z.string(),
  line: z.string(),
  from: z.string(),
  to: z.string(),
});

export const stopPointSchema = z.object({
  type: z.string(),
  id: z.string(),
  name: z.string(),
  naptanId: z.string(),
  lat: z.union([z.number(), z.string()]),
  lon: z.union([z.number(), z.string()]),
  modes: z.array(modeSchema),
  lines: z.array(z.string()),
});
