// Generated by ts-to-zod
import { z } from "zod";

export const genericEdgeSchema = z
  .object({
    from: z.string(),
    to: z.string(),
  })
  .and(z.record(z.any()));

export const genericVertexSchema = z
  .object({
    id: z.string(),
  })
  .and(z.record(z.any()));
