// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./GraphTypes";

export const literalSchema = z
  .union([z.string(), z.number(), z.boolean()])
  .nullable();

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z.union([literalSchema, z.record(jsonSchema), z.array(jsonSchema)])
);

export const genericVertexSchema = z
  .object({
    id: z.string(),
  })
  .and(jsonSchema);
