name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out source code
        uses: actions/checkout@v3
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        name: run npm install
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}        
      - run: npm run test:ci
        name: execute tests
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}          
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            message: ${{ steps.coverage.outputs.report }}
